# Generated by Django 5.0.4 on 2024-08-25 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 18, 8, 45, 384874), verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 18, 8, 45, 384874), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_editing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон'),
        ),
    ]
