# Generated by Django 5.0.4 on 2024-08-09 08:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название завода')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=100, verbose_name='Номер дома')),
                ('name_product', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('market_launch_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода продукта на рынок')),
                ('debt', models.IntegerField(default=0, verbose_name='Задолжность')),
                ('time_of_creation', models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 26, 19, 4908), verbose_name='Время создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название розничной сети')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=100, verbose_name='Номер дома')),
                ('name_product', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('market_launch_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода продукта на рынок')),
                ('debt', models.IntegerField(default=0, verbose_name='Задолжность')),
                ('time_of_creation', models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 26, 19, 5906), verbose_name='Время создания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factory', verbose_name='Поставщик')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_IE', models.CharField(max_length=100, verbose_name='Индивидуальный предприниматель')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=100, verbose_name='Номер дома')),
                ('name_product', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('market_launch_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода продукта на рынок')),
                ('debt', models.IntegerField(default=0, verbose_name='Задолжность')),
                ('time_of_creation', models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 26, 19, 6906), verbose_name='Время создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.retailnetwork', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
                'ordering': ('id',),
            },
        ),
    ]
