# Generated by Django 5.0.4 on 2024-08-26 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime(2024, 8, 27, 1, 47, 42, 140177), verbose_name='Дата создания')),
                ('date_of_editing', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Зоголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Изображение')),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime(2024, 8, 27, 1, 47, 42, 139172), verbose_name='Дата создания')),
                ('date_of_editing', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('id',),
            },
        ),
    ]
