# Generated by Django 5.0.4 on 2024-08-09 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 33, 32, 469300), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 33, 32, 471300), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 33, 32, 470300), verbose_name='Время создания'),
        ),
    ]
